
spring:
    application:
         name: paperservice-provider
    hsf:
        version: 1.0.0
        timeout: 30000
        serviceGroup: tiku
    datasource:
        url: jdbc:mysql://47.106.148.215:3306/exam?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
server:
  port: 8021

mybatis-plus:
  # 此处有坑 单模块加载也需要配置*(classpath 紧挨着的星) 解决自定义SQL无法执行
  mapper-locations: classpath*:mapping/*.xml
